### PR TITLE
Initial orogen component. Integrated vizkit3d_normal_depth_map and gp…

### PR DESCRIPTION
**Pull request by romulogcerqueira**
…u_sonar_simulation drivers. Until this moment, first tests were realized to show something in rock-display.

### CODE REVIEW

**Comment by doudou** [comment]
As far as I can see, this is made obsolete by https://github.com/Brazilian-Institute-of-Robotics/simulation-gpu_sonar_simulation/pull/2, or ?

**Comment by romulogcerqueira** [comment]
Hi Sylvain,

I didn't understand. This is the orogen component that uses gpu_sonar_simulation and vizkit3d_normal_depth_map drivers.

**Comment by doudou** [comment]
My mistake, sorry.

**Comment by romulogcerqueira** [comment]
I will delete this branch, because I am updating an another one (first_integration_test).

**Pull request closed without merging**
